import { BaziAnalysis, NameDetail, BabyInfo } from '@/types'

export const MOCK_BABY_INFO: BabyInfo = {
  lastName: '李',
  gender: 'boy',
  birthDate: '2024-03-15',
  birthTime: '14:30',
  birthCity: '北京',
  calendarType: 'solar',
}

export const MOCK_BAZI: BaziAnalysis = {
  bazi: {
    yearPillar: '甲辰',
    monthPillar: '丙寅',
    dayPillar: '戊午',
    hourPillar: '壬子',
    yearWuxing: '木土',
    monthWuxing: '火木',
    dayWuxing: '土火',
    hourWuxing: '水水',
    yearCanggan: '乙戊癸',
    monthCanggan: '甲丙戊',
    dayCanggan: '丁己',
    hourCanggan: '癸',
    yearNayin: '覆灯火',
    monthNayin: '炉中火',
    dayNayin: '天上火',
    hourNayin: '桑松木',
    benming: '龙',
  },
  wuxing: {
    gold: 1,
    wood: 3,
    water: 2,
    fire: 2,
    earth: 1,
    goldValue: 10,
    woodValue: 35,
    waterValue: 25,
    fireValue: 20,
    earthValue: 10,
    xiyong: ['火', '土'],
    jiyong: ['金', '水'],
    rizhu: '戊',
    rizhuWuxing: '土',
    tonglei: ['土', '火'],
    yilei: ['金', '水', '木'],
    tongleiScore: 40,
    yileiScore: 60,
    wangshuai: '身弱',
  },
  analysis: '测试分析结果：此命造身弱，喜火土。',
  suggestion: '建议起名选用五行属火、土的字。',
}

export const MOCK_NAME_DETAIL: NameDetail = {
  id: 'test-name-1',
  name: '煜宸',
  pinyin: 'yù chén',
  characters: [
    {
      char: '煜',
      pinyin: 'yù',
      wuxing: '火',
      meaning: '照耀，光辉灿烂',
      explanation: '火光照耀，寓意光明前途',
      source: '《说文解字》',
      kangxi: { strokes: 13, page: '第672页', original: '煜' },
    },
    {
      char: '宸',
      pinyin: 'chén',
      wuxing: '金',
      meaning: '帝王的住所，引申为尊贵',
      explanation: '宸极高远，寓意志向远大',
      source: '《康熙字典》',
      kangxi: { strokes: 10, page: '第286页', original: '宸' },
    },
  ],
  meaning: '光辉照耀九重宸殿，寓意前途光明、志存高远',
  source: '《诗经·大雅》',
  wuxing: '火金',
  baziMatch: '火为喜用神，补益命局，金泄土气平衡五行',
  score: 95,
  uniqueness: '较低',
  uniquenessCount: '500+',
  yinyun: {
    tone: '去声 阳平',
    initials: 'y ch',
    score: 92,
    analysis: '声调搭配和谐，抑扬顿挫，朗朗上口。',
  },
  personalizedMeaning: '煜宸寓意光芒万丈，志存高远，如日中天。',
  isLocked: false,
  style: '诗词雅韵',
}

export const MOCK_NAME_LIST: NameDetail[] = [
  MOCK_NAME_DETAIL,
  {
    ...MOCK_NAME_DETAIL,
    id: 'test-name-2',
    name: '晨曦',
    pinyin: 'chén xī',
    score: 93,
    isLocked: true,
  },
  {
    ...MOCK_NAME_DETAIL,
    id: 'test-name-3',
    name: '瑾瑜',
    pinyin: 'jǐn yú',
    score: 91,
    isLocked: true,
  },
]
